"""empty message

Revision ID: 23a9c3d79033
Revises: b97d7a062fe6
Create Date: 2020-01-18 13:46:45.528277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a9c3d79033'
down_revision = 'b97d7a062fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('tournament_status', sa.Enum('open', 'closed', 'waiting_results', name='tournamentstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'tournament_status')
    # ### end Alembic commands ###
