"""empty message

Revision ID: 27191ad36f11
Revises: 
Create Date: 2019-10-04 04:32:20.939856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27191ad36f11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('validated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'validated')
    # ### end Alembic commands ###
