"""empty message

Revision ID: 2f814518b15f
Revises: 104c8313c18f
Create Date: 2020-01-07 10:27:15.137627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f814518b15f'
down_revision = '104c8313c18f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('roi_rating', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('swap_rating', sa.Float(), nullable=True))
    op.drop_column('profiles', 'roi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('roi', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'swap_rating')
    op.drop_column('profiles', 'roi_rating')
    # ### end Alembic commands ###
