"""empty message

Revision ID: 30831bc96648
Revises: 7c30fb6392b2
Create Date: 2019-09-20 15:20:19.975059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30831bc96648'
down_revision = '7c30fb6392b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swaps', sa.Column('percentage', sa.Integer(), nullable=False))
    op.add_column('swaps', sa.Column('reciever_id', sa.Integer(), nullable=False))
    op.add_column('swaps', sa.Column('sender_id', sa.Integer(), nullable=False))
    op.add_column('swaps', sa.Column('tournament_id', sa.Integer(), nullable=False))
    op.add_column('swaps', sa.Column('winning_chips', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'swaps', 'tournaments', ['tournament_id'], ['id'])
    op.create_foreign_key(None, 'swaps', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'swaps', 'users', ['reciever_id'], ['id'])
    op.drop_column('swaps', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swaps', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'swaps', type_='foreignkey')
    op.drop_constraint(None, 'swaps', type_='foreignkey')
    op.drop_constraint(None, 'swaps', type_='foreignkey')
    op.drop_column('swaps', 'winning_chips')
    op.drop_column('swaps', 'tournament_id')
    op.drop_column('swaps', 'sender_id')
    op.drop_column('swaps', 'reciever_id')
    op.drop_column('swaps', 'percentage')
    # ### end Alembic commands ###
