"""empty message

Revision ID: 33a384f17807
Revises: 5948b2f7e5f6
Create Date: 2019-12-23 19:02:26.876694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33a384f17807'
down_revision = '5948b2f7e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zip_codes')
    op.alter_column('transactions', 'coins',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'coins',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('zip_codes',
    sa.Column('zip_code', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('zip_code', name='zip_codes_pkey')
    )
    # ### end Alembic commands ###
