"""empty message

Revision ID: 4128828e8307
Revises: 2ebbce1fda8b
Create Date: 2019-11-26 00:14:27.132439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4128828e8307'
down_revision = '2ebbce1fda8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('state', sa.String(length=20), nullable=True))
    op.add_column('tournaments', sa.Column('zip_code', sa.String(length=14), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'zip_code')
    op.drop_column('tournaments', 'state')
    # ### end Alembic commands ###
