"""empty message

Revision ID: 544bc9ea420e
Revises: 
Create Date: 2019-09-19 17:25:41.701584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '544bc9ea420e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buy_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pictures')
    op.drop_constraint('flights_ibfk_1', 'flights', type_='foreignkey')
    op.drop_column('flights', 'tournament_id')
    op.drop_column('flights', 'start_date')
    op.drop_column('flights', 'end_date')
    op.drop_column('flights', 'date_created')
    op.drop_constraint('profiles_ibfk_1', 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'first_name')
    op.drop_column('profiles', 'last_name')
    op.drop_column('profiles', 'date_created')
    op.drop_column('tournaments', 'start_date')
    op.drop_column('tournaments', 'end_date')
    op.drop_column('tournaments', 'date_created')
    op.drop_column('tournaments', 'name')
    op.drop_index('email', table_name='users')
    op.drop_index('password', table_name='users')
    op.drop_column('users', 'password')
    op.drop_column('users', 'date_created')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(collation='utf8mb4_general_ci', length=80), nullable=False))
    op.add_column('users', sa.Column('date_created', sa.DATE(), nullable=True))
    op.add_column('users', sa.Column('password', mysql.VARCHAR(collation='utf8mb4_general_ci', length=80), nullable=False))
    op.create_index('password', 'users', ['password'], unique=True)
    op.create_index('email', 'users', ['email'], unique=True)
    op.add_column('tournaments', sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=120), nullable=True))
    op.add_column('tournaments', sa.Column('date_created', sa.DATE(), nullable=True))
    op.add_column('tournaments', sa.Column('end_date', sa.DATE(), nullable=True))
    op.add_column('tournaments', sa.Column('start_date', sa.DATE(), nullable=True))
    op.add_column('profiles', sa.Column('date_created', sa.DATE(), nullable=True))
    op.add_column('profiles', sa.Column('last_name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=80), nullable=False))
    op.add_column('profiles', sa.Column('first_name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=80), nullable=False))
    op.create_foreign_key('profiles_ibfk_1', 'profiles', 'users', ['id'], ['id'])
    op.add_column('flights', sa.Column('date_created', sa.DATE(), nullable=True))
    op.add_column('flights', sa.Column('end_date', sa.DATE(), nullable=True))
    op.add_column('flights', sa.Column('start_date', sa.DATE(), nullable=True))
    op.add_column('flights', sa.Column('tournament_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('flights_ibfk_1', 'flights', 'tournaments', ['tournament_id'], ['id'])
    op.create_table('pictures',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('date_created', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='pictures_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('transactions')
    op.drop_table('tokens')
    op.drop_table('swaps')
    op.drop_table('buy_ins')
    # ### end Alembic commands ###
