"""empty message

Revision ID: 5b27c9c24fdc
Revises: 652b04d2ac10
Create Date: 2020-03-07 00:48:40.494276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b27c9c24fdc'
down_revision = '652b04d2ac10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('time_zone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'time_zone')
    # ### end Alembic commands ###
