"""empty message

Revision ID: 62807d520866
Revises: db57931a99f0
Create Date: 2019-12-18 06:24:06.145657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62807d520866'
down_revision = 'db57931a99f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('results_link', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'results_link')
    # ### end Alembic commands ###
