"""empty message

Revision ID: 6ce6e8c99a85
Revises: da28763e1d20
Create Date: 2019-10-20 14:08:44.093393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce6e8c99a85'
down_revision = 'da28763e1d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('roi', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'roi')
    # ### end Alembic commands ###
