"""empty message

Revision ID: 75c9b768c637
Revises: 58200e166e4e
Create Date: 2019-10-05 01:21:14.012569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c9b768c637'
down_revision = '58200e166e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swaps', sa.Column('paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swaps', 'paid')
    # ### end Alembic commands ###
