"""empty message

Revision ID: 7c30fb6392b2
Revises: fc99fd62486d
Create Date: 2019-09-20 14:42:43.449355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c30fb6392b2'
down_revision = 'fc99fd62486d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('tournament_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'flights', 'tournaments', ['tournament_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_column('flights', 'tournament_id')
    # ### end Alembic commands ###
