"""empty message

Revision ID: 840b6eb9fbbe
Revises: 92cd2880b7dc
Create Date: 2020-02-28 01:43:25.502045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840b6eb9fbbe'
down_revision = '92cd2880b7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
