"""empty message

Revision ID: 8a89a2deba35
Revises: 33a384f17807
Create Date: 2019-12-24 09:32:41.718511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a89a2deba35'
down_revision = '33a384f17807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swaps', sa.Column('cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swaps', 'cost')
    # ### end Alembic commands ###
