"""empty message

Revision ID: 8d2762d5c39c
Revises: a9c97148947f
Create Date: 2019-09-22 04:05:14.492011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2762d5c39c'
down_revision = 'a9c97148947f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_ins', sa.Column('flight_id', sa.Integer(), nullable=True))
    op.add_column('buy_ins', sa.Column('receipt_image_url', sa.String(length=250), nullable=True))
    op.add_column('buy_ins', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'buy_ins', 'profiles', ['user_id'], ['id'])
    op.create_foreign_key(None, 'buy_ins', 'flights', ['flight_id'], ['id'])
    op.drop_constraint('swaps_ibfk_2', 'swaps', type_='foreignkey')
    op.create_foreign_key(None, 'swaps', 'profiles', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'swaps', 'profiles', ['recipient_id'], ['id'])
    op.add_column('tokens', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('tokens', sa.Column('token', sa.String(length=500), nullable=True))
    op.add_column('tokens', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'])
    op.add_column('transactions', sa.Column('amount_in_coins', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('amount_in_dollars', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'user_id')
    op.drop_column('transactions', 'amount_in_dollars')
    op.drop_column('transactions', 'amount_in_coins')
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_column('tokens', 'user_id')
    op.drop_column('tokens', 'token')
    op.drop_column('tokens', 'expires_at')
    op.drop_constraint(None, 'swaps', type_='foreignkey')
    op.drop_constraint(None, 'swaps', type_='foreignkey')
    op.create_foreign_key('swaps_ibfk_2', 'swaps', 'users', ['sender_id'], ['id'])
    op.drop_constraint(None, 'buy_ins', type_='foreignkey')
    op.drop_constraint(None, 'buy_ins', type_='foreignkey')
    op.drop_column('buy_ins', 'user_id')
    op.drop_column('buy_ins', 'receipt_image_url')
    op.drop_column('buy_ins', 'flight_id')
    # ### end Alembic commands ###
