"""empty message

Revision ID: 8f6a63bfc917
Revises: 6ce6e8c99a85
Create Date: 2019-11-02 14:23:27.962965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f6a63bfc917'
down_revision = '6ce6e8c99a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('nickname', sa.String(length=100), nullable=True))
    op.drop_column('profiles', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('username', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True))
    op.drop_column('profiles', 'nickname')
    # ### end Alembic commands ###
