"""empty message

Revision ID: 92077e78790f
Revises: 5264af74acbf
Create Date: 2020-02-08 14:03:03.535843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92077e78790f'
down_revision = '5264af74acbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_ins', sa.Column('winnings', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buy_ins', 'winnings')
    # ### end Alembic commands ###
