"""empty message

Revision ID: 9484c0a4e181
Revises: 7d40966fb4f7
Create Date: 2019-11-27 17:48:11.757425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9484c0a4e181'
down_revision = '7d40966fb4f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swaps', 'winning_chips')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swaps', sa.Column('winning_chips', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
