"""empty message

Revision ID: 9c93ceb709b8
Revises: 8f6a63bfc917
Create Date: 2019-11-08 02:06:37.397962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c93ceb709b8'
down_revision = '8f6a63bfc917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_ins', sa.Column('place', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buy_ins', 'place')
    # ### end Alembic commands ###
