"""empty message

Revision ID: 9dccd16bd726
Revises: 816c362a18d9
Create Date: 2020-02-16 18:33:49.952951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dccd16bd726'
down_revision = '816c362a18d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_ins', sa.Column('player_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buy_ins', 'player_name')
    # ### end Alembic commands ###
