"""empty message

Revision ID: a9c97148947f
Revises: f28fa07f38ba
Create Date: 2019-09-20 21:38:41.842200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9c97148947f'
down_revision = 'f28fa07f38ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profiles_ibfk_1', 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'user_id')
    op.add_column('swaps', sa.Column('due_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swaps', 'due_at')
    op.add_column('profiles', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('profiles_ibfk_1', 'profiles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
