"""empty message

Revision ID: c1846b77f4ca
Revises: 320ce9d06ba6
Create Date: 2019-09-20 14:07:11.142301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1846b77f4ca'
down_revision = '320ce9d06ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('address', sa.String(length=250), nullable=True))
    op.add_column('tournaments', sa.Column('end_at', sa.DateTime(), nullable=True))
    op.add_column('tournaments', sa.Column('name', sa.String(length=500), nullable=False))
    op.add_column('tournaments', sa.Column('start_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'start_at')
    op.drop_column('tournaments', 'name')
    op.drop_column('tournaments', 'end_at')
    op.drop_column('tournaments', 'address')
    # ### end Alembic commands ###
