"""empty message

Revision ID: c2775414e442
Revises: 840b6eb9fbbe
Create Date: 2020-02-28 01:43:57.963710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2775414e442'
down_revision = '840b6eb9fbbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('day', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'day')
    # ### end Alembic commands ###
