"""empty message

Revision ID: d03a9ae2d343
Revises: f2a13c37bbfe
Create Date: 2019-10-05 04:27:20.316630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03a9ae2d343'
down_revision = 'f2a13c37bbfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('tournaments', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'longitude')
    op.drop_column('tournaments', 'latitude')
    # ### end Alembic commands ###
