"""empty message

Revision ID: da28763e1d20
Revises: ef99e65793ad
Create Date: 2019-10-08 09:12:06.937913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da28763e1d20'
down_revision = 'ef99e65793ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_ins', sa.Column('chips', sa.Integer(), nullable=True))
    op.add_column('buy_ins', sa.Column('seat', sa.Integer(), nullable=True))
    op.add_column('buy_ins', sa.Column('table', sa.Integer(), nullable=True))
    op.add_column('swaps', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swaps', 'status')
    op.drop_column('buy_ins', 'table')
    op.drop_column('buy_ins', 'seat')
    op.drop_column('buy_ins', 'chips')
    # ### end Alembic commands ###
