"""empty message

Revision ID: ef99e65793ad
Revises: 29661fa98129
Create Date: 2019-10-06 15:22:01.875547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef99e65793ad'
down_revision = '29661fa98129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_ins', sa.Column('receipt_img_url', sa.String(length=250), nullable=True))
    op.drop_column('buy_ins', 'receipt_image_url')
    op.add_column('profiles', sa.Column('profile_pic_url', sa.String(length=250), nullable=True))
    op.drop_column('profiles', 'profile_picture_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('profile_picture_url', mysql.VARCHAR(collation='utf8mb4_general_ci', length=250), nullable=True))
    op.drop_column('profiles', 'profile_pic_url')
    op.add_column('buy_ins', sa.Column('receipt_image_url', mysql.VARCHAR(collation='utf8mb4_general_ci', length=250), nullable=True))
    op.drop_column('buy_ins', 'receipt_img_url')
    # ### end Alembic commands ###
