"""empty message

Revision ID: f28fa07f38ba
Revises: 30831bc96648
Create Date: 2019-09-20 16:22:16.377492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f28fa07f38ba'
down_revision = '30831bc96648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swaps', sa.Column('recipient_id', sa.Integer(), nullable=False))
    op.drop_constraint('swaps_ibfk_3', 'swaps', type_='foreignkey')
    op.drop_column('swaps', 'reciever_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swaps', sa.Column('reciever_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('swaps_ibfk_3', 'swaps', 'users', ['reciever_id'], ['id'])
    op.drop_column('swaps', 'recipient_id')
    # ### end Alembic commands ###
